// ═══════════════════════════════════════════════════════════
// 1V9.AI — GAME DATA
// ═══════════════════════════════════════════════════════════

const TECHNIQUES = [
  // ── BEGINNER (FREE) ──────────────────────────────────────
  { id:'b1', name:'Last Hitting Basics', description:'Learn to time your auto attacks to secure minion kills and gold.', tier:'beginner', icon:'🗡️', xpReward:50, cost:0, category:'cs', tips:['Wait for minion HP to drop below your AD','Watch your attack animation wind-up','Prioritize cannon minions — worth more gold'], bestScore:0, completed:false },
  { id:'b2', name:'Last Hitting Under Tower', description:'Master the tower shot patterns to CS under pressure.', tier:'beginner', icon:'🏰', xpReward:60, cost:0, category:'cs', tips:['Melee minions: 2 tower shots + 1 auto','Caster minions: 1 auto + 1 tower shot + 1 auto','Prep casters with an auto before tower hits them'], bestScore:0, completed:false },
  { id:'b3', name:'Basic Ability Combos', description:'Chain your abilities in the right order for maximum damage.', tier:'beginner', icon:'💥', xpReward:50, cost:0, category:'combat', tips:['Learn your champion combo order','Use abilities between auto attacks','Practice the full rotation on dummies first'], bestScore:0, completed:false },
  { id:'b4', name:'Map Awareness Check', description:'Train yourself to glance at the minimap every few seconds.', tier:'beginner', icon:'🗺️', xpReward:40, cost:0, category:'macro', tips:['Check minimap every 5 seconds','Count enemy champions visible on map','Missing enemies = danger — play safe'], bestScore:0, completed:false },
  { id:'b5', name:'Trading Stance', description:'Position aggressively when the enemy goes to last hit a minion.', tier:'beginner', icon:'⚔️', xpReward:50, cost:0, category:'combat', tips:['Step forward when enemy reaches for CS','They must choose: CS or trade back','Back off after landing your damage'], bestScore:0, completed:false },
  { id:'b6', name:'Minion Wave Basics', description:'Understand how minion waves push and crash into towers.', tier:'beginner', icon:'🌊', xpReward:40, cost:0, category:'wave', tips:['More minions = wave pushes toward enemy','Killing minions fast pushes the wave','Letting minions die slowly pulls the wave'], bestScore:0, completed:false },
  { id:'b7', name:'Ward Placement 101', description:'Learn the essential ward spots to keep yourself safe.', tier:'beginner', icon:'👁️', xpReward:40, cost:0, category:'vision', tips:['Ward river bushes to see ganks coming','Place wards before they are needed','Trinket ward at 3:00 for first jungle gank'], bestScore:0, completed:false },
  { id:'b8', name:'Back Timing', description:'Learn when to recall without losing CS or plates.', tier:'beginner', icon:'🔙', xpReward:50, cost:0, category:'macro', tips:['Push wave into enemy tower before backing','Back with enough gold for a component item','Avoid backing with cannon wave approaching'], bestScore:0, completed:false },
  { id:'b9', name:'Objective Focus', description:'Prioritize dragons, heralds, and barons at the right times.', tier:'beginner', icon:'🐉', xpReward:50, cost:0, category:'macro', tips:['Take dragon after getting a kill bot lane','Herald is best used before 14 minutes','Baron after winning a team fight with 3+ alive'], bestScore:0, completed:false },
  { id:'b10', name:'Tower Aggro Management', description:'Understand how tower targeting works to dive and trade safely.', tier:'beginner', icon:'🔫', xpReward:40, cost:0, category:'combat', tips:['Towers target the closest enemy unit first','Attacking a champion draws tower aggro','Step out of tower range to drop aggro'], bestScore:0, completed:false },

  // ── INTERMEDIATE (25 CREDITS) ────────────────────────────
  { id:'i1', name:'Wave Freezing', description:'Hold the minion wave near your tower to deny CS and set up ganks.', tier:'intermediate', icon:'🧊', xpReward:80, cost:25, category:'wave', tips:['Keep 3-4 extra enemy caster minions alive','Only last hit — dont use abilities on wave','This denies CS and exposes enemy to ganks'], bestScore:0, completed:false },
  { id:'i2', name:'Slow Push Setup', description:'Build a massive wave that crashes for a tower dive or roam.', tier:'intermediate', icon:'📈', xpReward:80, cost:25, category:'wave', tips:['Kill just the caster minions to slow push','Takes 2-3 waves to build up','Use the big wave to dive or rotate to objective'], bestScore:0, completed:false },
  { id:'i3', name:'Fast Push Clear', description:'Instantly shove waves to create pressure and roam timers.', tier:'intermediate', icon:'⚡', xpReward:70, cost:25, category:'wave', tips:['Use all abilities to kill wave fast','Creates a window to roam or ward','Enemy loses CS to their tower'], bestScore:0, completed:false },
  { id:'i4', name:'Jungle Tracking', description:'Predict where the enemy jungler is based on CS count and timers.', tier:'intermediate', icon:'🔍', xpReward:90, cost:25, category:'macro', tips:['Check enemy jungler CS at first encounter','Each camp is roughly 4 CS','Track buff timers — they respawn at 5:00'], bestScore:0, completed:false },
  { id:'i5', name:'Roam Timing', description:'Know when to leave lane to impact other parts of the map.', tier:'intermediate', icon:'🏃', xpReward:80, cost:25, category:'macro', tips:['Roam after pushing wave into enemy tower','Roam when you see a fight about to happen','Dont roam if you will lose more than you gain'], bestScore:0, completed:false },
  { id:'i6', name:'Trading Patterns', description:'Execute multi-step trades that win through ability sequencing.', tier:'intermediate', icon:'🥊', xpReward:80, cost:25, category:'combat', tips:['Short trades: one ability + auto then back off','Extended trades: commit when you have ability advantage','Track enemy cooldowns to trade when they are down'], bestScore:0, completed:false },
  { id:'i7', name:'Zoning Control', description:'Use positioning to deny the enemy from CS or experience.', tier:'intermediate', icon:'🚧', xpReward:70, cost:25, category:'combat', tips:['Stand between enemy and their minions','Threaten with abilities if they walk up','Only zone when you have a health or item advantage'], bestScore:0, completed:false },
  { id:'i8', name:'Dive Execution', description:'Coordinate tower dives with proper aggro swapping.', tier:'intermediate', icon:'💀', xpReward:100, cost:25, category:'combat', tips:['Tanky champion takes first tower shot','Swap aggro by stepping out when low','Ensure the wave is crashing into tower before diving'], bestScore:0, completed:false },
  { id:'i9', name:'Dragon Setup', description:'Prepare vision and wave states before contesting dragon.', tier:'intermediate', icon:'🐲', xpReward:90, cost:25, category:'macro', tips:['Push bot and mid waves before dragon','Sweep and ward dragon pit 60s before spawn','Position your team on the approach path'], bestScore:0, completed:false },
  { id:'i10', name:'Vision Denial', description:'Use sweepers and control wards to blind the enemy.', tier:'intermediate', icon:'🕶️', xpReward:70, cost:25, category:'vision', tips:['Switch to sweeper after first back as support','Clear wards before objectives spawn','Control ward in bushes you want to hold'], bestScore:0, completed:false },

  // ── ADVANCED (PRO SUB) ───────────────────────────────────
  { id:'a1', name:'Animation Canceling', description:'Cancel ability animations to output damage faster than intended.', tier:'advanced', icon:'⚙️', xpReward:120, cost:50, category:'mechanics', tips:['Buffer movement commands between abilities','Many champions can cancel with auto resets','Riven Q-auto-Q-auto is a classic example'], bestScore:0, completed:false },
  { id:'a2', name:'Team Fight Positioning', description:'Stand in the optimal position based on your role in fights.', tier:'advanced', icon:'🎯', xpReward:120, cost:50, category:'combat', tips:['ADCs: stay at max attack range behind frontline','Assassins: flank and wait for key abilities to be used','Tanks: engage when your team can follow up'], bestScore:0, completed:false },
  { id:'a3', name:'Split Push Decisions', description:'Know when to split push vs group with your team.', tier:'advanced', icon:'🔀', xpReward:110, cost:50, category:'macro', tips:['Split when you win the 1v1 side lane','Group when your team needs you for objectives','Apply pressure then rotate if enemy sends 2+'], bestScore:0, completed:false },
  { id:'a4', name:'Lane State Management', description:'Manipulate the entire lane state across multiple waves.', tier:'advanced', icon:'🎼', xpReward:120, cost:50, category:'wave', tips:['Plan 3 waves ahead not just the current one','Set up slow pushes before objectives','Bounce waves off tower to get a freeze'], bestScore:0, completed:false },
  { id:'a5', name:'Multi-Man Dive', description:'Coordinate complex tower dives with 2-4 players.', tier:'advanced', icon:'👥', xpReward:130, cost:50, category:'combat', tips:['Assign aggro rotation before engaging','CC chain the target under tower','Have an exit plan if dive goes wrong'], bestScore:0, completed:false },
  { id:'a6', name:'Baron Power Play', description:'Convert baron buff into maximum map pressure and objectives.', tier:'advanced', icon:'👑', xpReward:130, cost:50, category:'macro', tips:['Split into 1-3-1 with baron buff','Empowered minions tank tower shots for you','Use buff to take 2+ towers, not just one'], bestScore:0, completed:false },
  { id:'a7', name:'Limit Testing', description:'Push your champion to the absolute limit to find kill thresholds.', tier:'advanced', icon:'🔥', xpReward:100, cost:50, category:'mechanics', tips:['Know your exact damage at each level','Practice all-ins in practice tool first','Ignite timing can make or break close fights'], bestScore:0, completed:false },
  { id:'a8', name:'Side Lane Pressure', description:'Apply cross-map pressure by threatening side lanes at the right time.', tier:'advanced', icon:'📡', xpReward:110, cost:50, category:'macro', tips:['Push side lane before grouping for objectives','Force enemy to respond to your pressure','TP advantage enables split + teamfight threat'], bestScore:0, completed:false },
  { id:'a9', name:'Engage Timing', description:'Find the perfect moment to start a team fight your team will win.', tier:'advanced', icon:'🚀', xpReward:120, cost:50, category:'combat', tips:['Engage when enemy uses key cooldowns','Fight around your power spikes','Dont engage if your team is still rotating'], bestScore:0, completed:false },
  { id:'a10', name:'Win Condition ID', description:'Identify and play toward your teams win condition each game.', tier:'advanced', icon:'🏆', xpReward:130, cost:50, category:'macro', tips:['Ask: how does my team win fights?','Play around your fed carry','Adapt strategy based on team comp strengths'], bestScore:0, completed:false }
];

const CHAMPIONS = [
  { name:'Ahri', icon:'🦊', roles:['mid'], winRate:'52.1%', pickRate:'8.4%', banRate:'5.2%', tier:'S', difficulty:2, coreItems:['Ludens Companion','Shadowflame','Rabadons Deathcap'], counters:['Yasuo','Kassadin','Fizz'], synergies:['Amumu','Jarvan IV','Leona'], tips:'Use charm to catch enemies out of position. R resets on takedowns — chain dashes in teamfights.' },
  { name:'Akali', icon:'🥷', roles:['mid','top'], winRate:'49.8%', pickRate:'7.1%', banRate:'12.3%', tier:'A', difficulty:3, coreItems:['Hextech Rocketbelt','Shadowflame','Zhonyas Hourglass'], counters:['Galio','Kassadin','Annie'], synergies:['Nautilus','Jarvan IV','Orianna'], tips:'Use shroud to trade safely. E1 backward then E2 forward is a key engage tool.' },
  { name:'Aatrox', icon:'⚔️', roles:['top'], winRate:'51.3%', pickRate:'9.2%', banRate:'14.1%', tier:'S', difficulty:2, coreItems:['Eclipse','Black Cleaver','Deaths Dance'], counters:['Fiora','Vayne','Irelia'], synergies:['Lulu','Yuumi','Zilean'], tips:'Hit sweet spots on Q for bonus damage and healing. W pull combos with Q2 or Q3.' },
  { name:'Aphelios', icon:'🌙', roles:['adc'], winRate:'48.5%', pickRate:'5.3%', banRate:'3.1%', tier:'B', difficulty:3, coreItems:['Infinity Edge','Runaans Hurricane','Bloodthirster'], counters:['Draven','Caitlyn','Tristana'], synergies:['Thresh','Lulu','Nautilus'], tips:'Manage weapon rotation. Gravitum + Infernum ult is devastating in teamfights.' },
  { name:'Ashe', icon:'❄️', roles:['adc','support'], winRate:'52.4%', pickRate:'10.1%', banRate:'2.8%', tier:'A', difficulty:1, coreItems:['Kraken Slayer','Blade of the Ruined King','Runaans Hurricane'], counters:['Sivir','Samira','Lucian'], synergies:['Zyra','Brand','Leona'], tips:'Use W to poke in lane. Global R is a game-changing engage or pick tool from any distance.' },
  { name:'Azir', icon:'☀️', roles:['mid'], winRate:'47.8%', pickRate:'3.2%', banRate:'1.5%', tier:'C', difficulty:3, coreItems:['Nashors Tooth','Ludens Companion','Zhonyas Hourglass'], counters:['Xerath','Viktor','Syndra'], synergies:['Jarvan IV','Amumu','Leona'], tips:'WEQ combo for long-range engage. Shurima Shuffle (WEQ into R) is a game-winning play.' },
  { name:'Blitzcrank', icon:'🤖', roles:['support'], winRate:'51.8%', pickRate:'6.7%', banRate:'18.5%', tier:'A', difficulty:2, coreItems:['Locket of the Iron Solari','Knights Vow','Zekes Convergence'], counters:['Morgana','Sivir','Ezreal'], synergies:['Draven','Jinx','Miss Fortune'], tips:'Roam mid after pushing wave. The threat of hook zones enemies even without landing it.' },
  { name:'Brand', icon:'🔥', roles:['support','mid'], winRate:'52.7%', pickRate:'5.8%', banRate:'7.3%', tier:'A', difficulty:2, coreItems:['Liandries Anguish','Rylais Crystal Scepter','Demonic Embrace'], counters:['Xerath','Vel\'Koz','Zyra'], synergies:['Amumu','Yasuo','Miss Fortune'], tips:'Stack passive for huge AOE damage. R bounces more in tight groups — fight in jungle chokes.' },
  { name:'Caitlyn', icon:'🎯', roles:['adc'], winRate:'51.5%', pickRate:'11.2%', banRate:'6.8%', tier:'S', difficulty:2, coreItems:['Infinity Edge','Rapid Firecannon','The Collector'], counters:['Sivir','Samira','Draven'], synergies:['Lux','Morgana','Zyra'], tips:'Abuse range advantage early. EQ combo on trapped enemies for burst. Control vision with traps.' },
  { name:'Camille', icon:'🦿', roles:['top'], winRate:'50.9%', pickRate:'6.4%', banRate:'8.9%', tier:'A', difficulty:3, coreItems:['Trinity Force','Ravenous Hydra','Deaths Dance'], counters:['Jax','Darius','Renekton'], synergies:['Orianna','Lulu','Ivern'], tips:'E flash extends hookshot range. W poke in lane heals you. R isolates key targets in teamfights.' },
  { name:'Darius', icon:'🪓', roles:['top'], winRate:'51.6%', pickRate:'7.8%', banRate:'11.2%', tier:'A', difficulty:1, coreItems:['Trinity Force','Dead Mans Plate','Steraks Gage'], counters:['Vayne','Quinn','Kayle'], synergies:['Yuumi','Lulu','Morgana'], tips:'Stack passive to 5 then R for max true damage. Ghost is essential for sticking to targets.' },
  { name:'Diana', icon:'🌑', roles:['jungle','mid'], winRate:'51.2%', pickRate:'6.1%', banRate:'4.5%', tier:'A', difficulty:2, coreItems:['Nashors Tooth','Shadowflame','Zhonyas Hourglass'], counters:['Graves','Vi','Lee Sin'], synergies:['Yasuo','Orianna','Malphite'], tips:'R in teamfights after grouping enemies with E pull. Flash R for surprise 5-man engages.' },
  { name:'Draven', icon:'🪙', roles:['adc'], winRate:'50.4%', pickRate:'5.9%', banRate:'7.1%', tier:'B', difficulty:3, coreItems:['Infinity Edge','Bloodthirster','Lord Dominiks Regards'], counters:['Caitlyn','Ezreal','Tristana'], synergies:['Nautilus','Thresh','Leona'], tips:'Catch axes to maintain passive stacks. Cash in on first kill for massive gold lead.' },
  { name:'Ezreal', icon:'✨', roles:['adc'], winRate:'49.5%', pickRate:'14.8%', banRate:'3.2%', tier:'B', difficulty:2, coreItems:['Trinity Force','Muramana','Serylda\'s Grudge'], counters:['Draven','Lucian','Kalista'], synergies:['Karma','Yuumi','Nami'], tips:'Poke with Q to stack tear and sheen. E defensively unless you are sure of the kill.' },
  { name:'Fiora', icon:'🤺', roles:['top'], winRate:'51.1%', pickRate:'5.7%', banRate:'8.4%', tier:'A', difficulty:3, coreItems:['Ravenous Hydra','Trinity Force','Deaths Dance'], counters:['Malphite','Kennen','Quinn'], synergies:['Lulu','Orianna','Karma'], tips:'Parry (W) enemy CC for a free stun. Proc all 4 vital marks of R for massive healing zone.' },
  { name:'Garen', icon:'🛡️', roles:['top'], winRate:'52.8%', pickRate:'6.9%', banRate:'3.5%', tier:'A', difficulty:1, coreItems:['Trinity Force','Dead Mans Plate','Force of Nature'], counters:['Vayne','Quinn','Camille'], synergies:['Yuumi','Lulu','Morgana'], tips:'Q removes slows and silences. Bush trading with Q-E then backing off is strong in lane.' },
  { name:'Graves', icon:'🔫', roles:['jungle'], winRate:'51.4%', pickRate:'7.3%', banRate:'5.6%', tier:'A', difficulty:2, coreItems:['Eclipse','The Collector','Infinity Edge'], counters:['Rammus','Amumu','Sejuani'], synergies:['Nautilus','Leona','Camille'], tips:'Auto-E-auto for burst. Smoke screen (W) denies vision in teamfights. Kite camps with E dash.' },
  { name:'Hecarim', icon:'🐴', roles:['jungle'], winRate:'51.7%', pickRate:'5.4%', banRate:'6.8%', tier:'A', difficulty:2, coreItems:['Trinity Force','Deaths Dance','Spirit Visage'], counters:['Lillia','Kindred','Graves'], synergies:['Orianna','Karma','Zilean'], tips:'Ghost + E charge for terrifying ganks. R fear into team for devastating engage.' },
  { name:'Irelia', icon:'🗡️', roles:['top','mid'], winRate:'49.2%', pickRate:'7.8%', banRate:'15.6%', tier:'A', difficulty:3, coreItems:['Blade of the Ruined King','Trinity Force','Wits End'], counters:['Trundle','Volibear','Sett'], synergies:['Lulu','Yuumi','Orianna'], tips:'Stack passive on minions before fighting. Q reset on marked or low HP targets is key.' },
  { name:'Jax', icon:'🏮', roles:['top','jungle'], winRate:'51.5%', pickRate:'6.2%', banRate:'9.1%', tier:'A', difficulty:2, coreItems:['Trinity Force','Blade of the Ruined King','Spear of Shojin'], counters:['Malphite','Garen','Kennen'], synergies:['Lulu','Kayle','Zilean'], tips:'E blocks all auto attacks. Q onto ward for escape. Scale to become an unstoppable split pusher.' },
  { name:'Jinx', icon:'💣', roles:['adc'], winRate:'51.9%', pickRate:'12.5%', banRate:'5.4%', tier:'S', difficulty:2, coreItems:['Infinity Edge','Runaans Hurricane','Rapid Firecannon'], counters:['Draven','Lucian','Samira'], synergies:['Thresh','Nautilus','Lulu'], tips:'Get Excited passive resets on takedowns. Switch to rockets in teamfights for AOE splash damage.' },
  { name:'Kai\'Sa', icon:'🦋', roles:['adc'], winRate:'50.3%', pickRate:'13.1%', banRate:'4.7%', tier:'A', difficulty:2, coreItems:['Kraken Slayer','Nashors Tooth','Zhonyas Hourglass'], counters:['Caitlyn','Draven','Miss Fortune'], synergies:['Nautilus','Thresh','Leona'], tips:'Evolve Q first (AD items), then E (AS items). R into backline when they are isolated.' },
  { name:'Katarina', icon:'🗡️', roles:['mid'], winRate:'49.7%', pickRate:'6.8%', banRate:'10.2%', tier:'B', difficulty:3, coreItems:['Hextech Rocketbelt','Nashors Tooth','Zhonyas Hourglass'], counters:['Galio','Diana','Kassadin'], synergies:['Nautilus','Leona','Amumu'], tips:'Wait for enemy CC to be used before going in. E to daggers for instant damage procs.' },
  { name:'Kha\'Zix', icon:'🦗', roles:['jungle'], winRate:'51.3%', pickRate:'7.5%', banRate:'8.9%', tier:'A', difficulty:2, coreItems:['Duskblade of Draktharr','Edge of Night','Serpents Fang'], counters:['Rammus','Lee Sin','Elise'], synergies:['Orianna','Leona','Nautilus'], tips:'Isolate targets for bonus Q damage. Evolve Q first, then E or R depending on game state.' },
  { name:'Lee Sin', icon:'🥋', roles:['jungle'], winRate:'48.9%', pickRate:'11.4%', banRate:'9.7%', tier:'B', difficulty:3, coreItems:['Eclipse','Black Cleaver','Deaths Dance'], counters:['Rammus','Amumu','Sejuani'], synergies:['Orianna','Yasuo','Syndra'], tips:'InSec combo: ward hop behind enemy then R them into your team. Fall off late so close early.' },
  { name:'Leona', icon:'☀️', roles:['support'], winRate:'51.6%', pickRate:'8.9%', banRate:'6.3%', tier:'A', difficulty:1, coreItems:['Locket of the Iron Solari','Knights Vow','Zekes Convergence'], counters:['Morgana','Janna','Braum'], synergies:['Miss Fortune','Jinx','Samira'], tips:'E-Q combo locks enemies for 2+ seconds. Engage when ADC is in position to follow up.' },
  { name:'Lulu', icon:'🧚', roles:['support'], winRate:'52.3%', pickRate:'7.2%', banRate:'8.1%', tier:'S', difficulty:1, coreItems:['Moonstone Renewer','Staff of Flowing Water','Ardent Censer'], counters:['Zyra','Brand','Sona'], synergies:['Jinx','Kog\'Maw','Vayne'], tips:'Polymorph (W) shuts down assassins. R your carry in teamfights for the health buff and knockup.' },
  { name:'Lux', icon:'💡', roles:['support','mid'], winRate:'52.0%', pickRate:'9.3%', banRate:'7.5%', tier:'A', difficulty:1, coreItems:['Ludens Companion','Shadowflame','Rabadons Deathcap'], counters:['Fizz','Yasuo','Katarina'], synergies:['Caitlyn','Miss Fortune','Jinx'], tips:'Q-E-R combo one-shots squishies. Use E for vision in bushes. Bind catches win games.' },
  { name:'Miss Fortune', icon:'💰', roles:['adc'], winRate:'52.5%', pickRate:'10.7%', banRate:'4.9%', tier:'S', difficulty:1, coreItems:['The Collector','Infinity Edge','Lord Dominiks Regards'], counters:['Samira','Draven','Sivir'], synergies:['Leona','Nautilus','Amumu'], tips:'R in chokepoints for max damage. Double Up (Q) through dead minions bounces to enemy champions.' },
  { name:'Morgana', icon:'👼', roles:['support','mid'], winRate:'51.8%', pickRate:'7.1%', banRate:'10.8%', tier:'A', difficulty:1, coreItems:['Zhonyas Hourglass','Liandries Anguish','Rylais Crystal Scepter'], counters:['Zyra','Brand','Vel\'Koz'], synergies:['Caitlyn','Jinx','Jhin'], tips:'Black Shield (E) blocks CC on your carry. Q binding lasts 3s max rank — follow up fast.' },
  { name:'Nami', icon:'🌊', roles:['support'], winRate:'52.6%', pickRate:'6.8%', banRate:'3.4%', tier:'A', difficulty:2, coreItems:['Moonstone Renewer','Staff of Flowing Water','Ardent Censer'], counters:['Zyra','Brand','Blitzcrank'], synergies:['Lucian','Ezreal','Jhin'], tips:'W bounces between allies and enemies — position to maximize bounces. E empowers ally autos.' },
  { name:'Nautilus', icon:'⚓', roles:['support'], winRate:'51.4%', pickRate:'9.5%', banRate:'11.2%', tier:'A', difficulty:1, coreItems:['Locket of the Iron Solari','Knights Vow','Zekes Convergence'], counters:['Morgana','Janna','Braum'], synergies:['Jinx','Kai\'Sa','Aphelios'], tips:'R is point-and-click knockup engage. Hook-auto-E is devastating all-in combo at level 2.' },
  { name:'Orianna', icon:'⚙️', roles:['mid'], winRate:'50.5%', pickRate:'5.1%', banRate:'2.3%', tier:'B', difficulty:2, coreItems:['Ludens Companion','Shadowflame','Rabadons Deathcap'], counters:['Fizz','Yasuo','Katarina'], synergies:['Hecarim','Malphite','Diana'], tips:'Ball delivery with allies creates devastating shockwaves. QW combo pokes hard in lane.' },
  { name:'Pyke', icon:'🔪', roles:['support'], winRate:'49.9%', pickRate:'5.6%', banRate:'9.8%', tier:'B', difficulty:3, coreItems:['Duskblade of Draktharr','Edge of Night','Umbral Glaive'], counters:['Nautilus','Leona','Tahm Kench'], synergies:['Draven','Miss Fortune','Lucian'], tips:'R execute threshold resets and shares gold. Roam mid after level 6 for double gold kills.' },
  { name:'Riven', icon:'💨', roles:['top'], winRate:'50.2%', pickRate:'5.8%', banRate:'6.5%', tier:'B', difficulty:3, coreItems:['Eclipse','Black Cleaver','Deaths Dance'], counters:['Renekton','Poppy','Malphite'], synergies:['Lulu','Ivern','Orianna'], tips:'Fast Q combo: Q-auto-Q-auto-Q-auto. E shields enable aggressive trades. Animation cancel everything.' },
  { name:'Samira', icon:'🌹', roles:['adc'], winRate:'50.8%', pickRate:'7.3%', banRate:'12.7%', tier:'A', difficulty:3, coreItems:['Infinity Edge','Bloodthirster','The Collector'], counters:['Caitlyn','Ashe','Tristana'], synergies:['Nautilus','Leona','Rell'], tips:'Build S rank style meter then R. W blocks projectiles like Windwall. Passive dashes to knocked-up enemies.' },
  { name:'Senna', icon:'💚', roles:['support','adc'], winRate:'51.3%', pickRate:'8.2%', banRate:'5.1%', tier:'A', difficulty:2, coreItems:['Eclipse','Rapid Firecannon','Infinity Edge'], counters:['Blitzcrank','Nautilus','Leona'], synergies:['Tahm Kench','Sett','Seraphine'], tips:'Collect souls from minions you DONT kill. Q heals allies and damages enemies in a line.' },
  { name:'Sett', icon:'👊', roles:['top','support'], winRate:'51.7%', pickRate:'6.4%', banRate:'5.8%', tier:'A', difficulty:1, coreItems:['Blade of the Ruined King','Stridebreaker','Deaths Dance'], counters:['Quinn','Vayne','Kennen'], synergies:['Orianna','Yasuo','Lulu'], tips:'W true damage grit bar is your outplay tool. Flash R to slam priority target into their team.' },
  { name:'Syndra', icon:'🔮', roles:['mid'], winRate:'50.1%', pickRate:'4.8%', banRate:'3.9%', tier:'B', difficulty:2, coreItems:['Ludens Companion','Shadowflame','Rabadons Deathcap'], counters:['Fizz','Yasuo','Katarina'], synergies:['Vi','Jarvan IV','Elise'], tips:'Stack balls then R for maximum damage. E stuns through Q balls for long range CC.' },
  { name:'Thresh', icon:'⛓️', roles:['support'], winRate:'50.7%', pickRate:'11.8%', banRate:'7.9%', tier:'A', difficulty:3, coreItems:['Locket of the Iron Solari','Knights Vow','Zekes Convergence'], counters:['Morgana','Janna','Zyra'], synergies:['Samira','Jinx','Kai\'Sa'], tips:'Lantern saves lives — throw it to allies in danger. Flay direction matters: pull or push enemies.' },
  { name:'Tristana', icon:'💥', roles:['adc','mid'], winRate:'51.2%', pickRate:'6.5%', banRate:'3.8%', tier:'A', difficulty:2, coreItems:['Kraken Slayer','Infinity Edge','Rapid Firecannon'], counters:['Ezreal','Kai\'Sa','Vayne'], synergies:['Leona','Nautilus','Thresh'], tips:'W resets on E detonation and kills. All-in at level 2 with E bomb is devastating.' },
  { name:'Twisted Fate', icon:'🃏', roles:['mid'], winRate:'50.3%', pickRate:'4.2%', banRate:'5.1%', tier:'B', difficulty:2, coreItems:['Rapid Firecannon','Ludens Companion','Lich Bane'], counters:['Fizz','Yasuo','Kassadin'], synergies:['Elise','Pantheon','Nocturne'], tips:'Gold card point-and-click stun enables ganks. R to side lanes after shoving mid wave.' },
  { name:'Varus', icon:'🏹', roles:['adc','mid'], winRate:'50.6%', pickRate:'5.7%', banRate:'2.9%', tier:'B', difficulty:2, coreItems:['Muramana','Ludens Companion','Shadowflame'], counters:['Sivir','Samira','Lucian'], synergies:['Leona','Nautilus','Zyra'], tips:'R engage spreads to nearby enemies. Poke build: Q max range does massive damage.' },
  { name:'Vayne', icon:'🦇', roles:['adc','top'], winRate:'51.0%', pickRate:'8.9%', banRate:'10.3%', tier:'A', difficulty:3, coreItems:['Blade of the Ruined King','Kraken Slayer','Infinity Edge'], counters:['Draven','Caitlyn','Miss Fortune'], synergies:['Lulu','Nami','Thresh'], tips:'Silver bolts proc every 3rd hit for % max HP true damage. Condemn into walls stuns.' },
  { name:'Vi', icon:'👊', roles:['jungle'], winRate:'51.8%', pickRate:'5.9%', banRate:'4.2%', tier:'A', difficulty:1, coreItems:['Eclipse','Black Cleaver','Deaths Dance'], counters:['Graves','Kindred','Elise'], synergies:['Caitlyn','Jinx','Yasuo'], tips:'R is unstoppable point-and-click lockdown. Q flash redirects for surprise engages.' },
  { name:'Viktor', icon:'⚡', roles:['mid'], winRate:'50.8%', pickRate:'4.5%', banRate:'3.1%', tier:'B', difficulty:2, coreItems:['Ludens Companion','Shadowflame','Rabadons Deathcap'], counters:['Fizz','Katarina','Kassadin'], synergies:['Jarvan IV','Amumu','Leona'], tips:'Upgrade E first for wave clear. W gravity field zones enemies out of areas.' },
  { name:'Yasuo', icon:'🌪️', roles:['mid','adc'], winRate:'49.5%', pickRate:'10.5%', banRate:'18.9%', tier:'B', difficulty:3, coreItems:['Kraken Slayer','Infinity Edge','Deaths Dance'], counters:['Renekton','Pantheon','Annie'], synergies:['Diana','Malphite','Alistar'], tips:'Windwall blocks all projectiles. Stack Q tornado then engage with R on knockups from ANY source.' },
  { name:'Yone', icon:'👹', roles:['mid','top'], winRate:'50.1%', pickRate:'9.8%', banRate:'16.4%', tier:'A', difficulty:2, coreItems:['Kraken Slayer','Infinity Edge','Deaths Dance'], counters:['Renekton','Pantheon','Akali'], synergies:['Diana','Malphite','Orianna'], tips:'E snap-back is your safety net. Q3+R for massive teamfight engage. Mixed damage is hard to itemize against.' },
  { name:'Zed', icon:'🌑', roles:['mid'], winRate:'50.4%', pickRate:'8.7%', banRate:'21.5%', tier:'A', difficulty:3, coreItems:['Duskblade of Draktharr','Youmuus Ghostblade','Serpents Fang'], counters:['Zhonyas builders','Lissandra','Malzahar'], synergies:['Nautilus','Leona','Amumu'], tips:'WEQ poke in lane. R dodges abilities if timed right. Triple shuriken combo for one-shot.' },
  { name:'Zeri', icon:'⚡', roles:['adc'], winRate:'48.2%', pickRate:'4.1%', banRate:'2.8%', tier:'C', difficulty:2, coreItems:['Trinity Force','Runaans Hurricane','Infinity Edge'], counters:['Caitlyn','Draven','Miss Fortune'], synergies:['Lulu','Yuumi','Thresh'], tips:'R gives massive move speed in teamfights. E through walls for unique positioning. Kite constantly.' }
];

const TIER_LIST = {
  S: ['Ahri','Aatrox','Caitlyn','Jinx','Lulu','Miss Fortune'],
  A: ['Akali','Ashe','Blitzcrank','Brand','Camille','Darius','Diana','Fiora','Garen','Graves','Hecarim','Irelia','Jax','Kai\'Sa','Kha\'Zix','Leona','Lux','Morgana','Nami','Nautilus','Samira','Senna','Sett','Thresh','Tristana','Vayne','Vi','Yone','Zed'],
  B: ['Aphelios','Draven','Ezreal','Katarina','Lee Sin','Orianna','Pyke','Riven','Syndra','Twisted Fate','Varus','Viktor','Yasuo'],
  C: ['Azir','Zeri'],
  D: []
};

const TFT_COMPS = [
  { name:'Arcana Syndicate', tier:'S', units:['Ahri','Jinx','Hecarim','Brand','Nautilus','Varus','Twisted Fate','Xerath'], items:'Ahri: JG + Rabadons + Gunblade | Jinx: IE + LW + Runaans', description:'Fast 8 and roll for Ahri 2. Jinx secondary carry. Arcana trait gives AP and crit.', winRate:'1st — 18.2%' },
  { name:'Bruiser Bastion', tier:'S', units:['Sett','Darius','Vi','Aatrox','Jax','Irelia','Garen','Camille'], items:'Sett: BT + Titans + Warmogs | Aatrox: Gunblade + QSS', description:'Slow roll at 7 for Sett 3. Extremely tanky frontline with Sett carry.', winRate:'1st — 16.5%' },
  { name:'Sniper Academy', tier:'A', units:['Caitlyn','Ashe','Jinx','Lux','Ezreal','Akali','Senna','Vayne'], items:'Caitlyn: IE + LW + GS | Ashe: Rageblade + Runaans', description:'Backline carry comp. Position carefully against assassins. Strong with sniper trait active.', winRate:'1st — 14.8%' },
  { name:'Shadow Assassins', tier:'A', units:['Zed','Akali','Katarina','Pyke','Kha\'Zix','Diana','Lee Sin','Kayn'], items:'Zed: IE + BT + Edge of Night | Akali: JG + Gunblade', description:'Assassin jump to backline. Zed or Akali primary carry. Weak to clumped frontline comps.', winRate:'1st — 13.1%' },
  { name:'Enchanter Protect', tier:'A', units:['Lulu','Nami','Morgana','Senna','Jinx','Thresh','Karma','Sona'], items:'Jinx: IE + Runaans + GS | Lulu: Redemption + Chalice', description:'Shield and heal the carry. Enchanter buff makes team unkillable late game.', winRate:'1st — 12.9%' },
  { name:'Mage Burst', tier:'A', units:['Brand','Viktor','Syndra','Lux','Orianna','Ahri','Azir','Twisted Fate'], items:'Brand: JG + Rabadons + Gunblade | Viktor: Shojin + JG', description:'Double mage trait for extra casts. AOE damage melts grouped teams.', winRate:'1st — 12.3%' },
  { name:'Duelist Blademaster', tier:'B', units:['Fiora','Irelia','Yasuo','Yone','Samira','Jax','Camille','Riven'], items:'Yasuo: IE + BT + QSS | Irelia: Rageblade + Titans', description:'Auto-attack focused comp. Duelist gives attack speed stacking. Strong 1v1 but weak to CC.', winRate:'1st — 10.7%' },
  { name:'Recon Infiltrator', tier:'B', units:['Kai\'Sa','Vayne','Akali','Zed','Kha\'Zix','Pyke','Ezreal','Graves'], items:'Kai\'Sa: Rageblade + GS + Runaans | Vayne: Rageblade + RB', description:'Hybrid damage comp. Recon trait repositions carries. Flexible item usage.', winRate:'1st — 9.8%' }
];

const NEWS_ITEMS = [
  { title:'Patch 14.24 Breakdown: ADC Items Reworked', tag:'patch', excerpt:'Massive changes to Infinity Edge, Kraken Slayer, and Bloodthirster shake up the bot lane meta. Our AI predicts Jinx and Caitlyn as the biggest winners.', date:'APR 2, 2026' },
  { title:'T1 Faker Picks Ahri in Grand Finals — Full Analysis', tag:'esports', excerpt:'Faker locks in Ahri for the first time this split and delivers a masterclass. We break down every decision with AI replay analysis.', date:'APR 1, 2026' },
  { title:'The Aatrox Problem: Why Top Lane is Dominated by One Champion', tag:'meta', excerpt:'Aatrox has maintained a 51%+ win rate for 6 consecutive patches. Our neural engine identifies the core issue: sustain itemization.', date:'MAR 30, 2026' },
  { title:'How to Climb from Gold to Platinum in 30 Days', tag:'guide', excerpt:'Our AI analyzed 50,000 players who climbed from Gold to Plat. Here are the 5 common habits they all developed during their climb.', date:'MAR 28, 2026' },
  { title:'New Champion Reveal: Ambessa Medarda Abilities Leaked', tag:'patch', excerpt:'Riot teases the next champion joining the roster. Early data suggests a bruiser-assassin hybrid with terrain manipulation abilities.', date:'MAR 27, 2026' },
  { title:'MSI 2026 Format Changes Announced', tag:'esports', excerpt:'Riot reveals a new Swiss-system group stage format for MSI. Teams react with mixed opinions on the competitive implications.', date:'MAR 25, 2026' },
  { title:'Support Meta Shift: Enchanters Rising, Tanks Falling', tag:'meta', excerpt:'Lulu, Nami, and Karma now dominate the support tier list. Our analysis shows why the enchanter item buffs changed everything.', date:'MAR 23, 2026' },
  { title:'Wave Management Masterclass: The #1 Skill for Climbing', tag:'guide', excerpt:'Data from 100,000 games proves wave management is the highest-correlation skill for rank climbing. Here is exactly how to learn it.', date:'MAR 22, 2026' },
  { title:'$1V9 Token Surges 200% After Training Platform Launch', tag:'meta', excerpt:'The 1V9.AI meme coin sees massive volume as the training arena goes live. Community rewards program drives adoption among League players.', date:'MAR 20, 2026' },
  { title:'TFT Set 12 PBE: First Look at New Traits', tag:'patch', excerpt:'Teamfight Tactics Set 12 hits PBE with 8 new traits including Arcana, Bastion, and Recon. We rank every trait from best to worst.', date:'MAR 18, 2026' }
];

const LEADERBOARD = [
  { rank:1, name:'xXDarkCarryXx', score:48750, level:47, title:'Challenger' },
  { rank:2, name:'NeuralSmite', score:45200, level:44, title:'Challenger' },
  { rank:3, name:'1v9_or_FF15', score:42800, level:42, title:'Grandmaster' },
  { rank:4, name:'MidDiffGG', score:39400, level:39, title:'Grandmaster' },
  { rank:5, name:'CS_PerfectBot', score:37100, level:37, title:'Grandmaster' },
  { rank:6, name:'JungleTrackerAI', score:35600, level:35, title:'Master' },
  { rank:7, name:'WardMother99', score:33200, level:33, title:'Master' },
  { rank:8, name:'FlashOnD_Always', score:31800, level:31, title:'Master' },
  { rank:9, name:'BaronStealQueen', score:29500, level:29, title:'Master' },
  { rank:10, name:'FreezeFrameTop', score:27100, level:27, title:'Diamond' },
  { rank:11, name:'E_Girl_Lux_OTP', score:25800, level:25, title:'Diamond' },
  { rank:12, name:'KiteGod_ADC', score:24300, level:24, title:'Diamond' },
  { rank:13, name:'GankMeOneMore', score:22900, level:22, title:'Diamond' },
  { rank:14, name:'SupportCarry420', score:21500, level:21, title:'Emerald' },
  { rank:15, name:'TeemoSatanMain', score:20100, level:20, title:'Emerald' },
  { rank:16, name:'PentakillPlease', score:18700, level:18, title:'Emerald' },
  { rank:17, name:'BotDiff_Report', score:17300, level:17, title:'Emerald' },
  { rank:18, name:'ARAMisLife', score:15900, level:15, title:'Platinum' },
  { rank:19, name:'ProxySinged420', score:14500, level:14, title:'Platinum' },
  { rank:20, name:'YasuoPowerspike', score:13100, level:13, title:'Platinum' }
];

const CLIPS = [
  { title:'Faker-Level Ahri Charm Prediction', author:'xXDarkCarryXx', views:'24.5K', likes:'1.8K', icon:'🦊', description:'Insane charm prediction through fog of war for the pentakill' },
  { title:'The Perfect 10 CS/min Guide', author:'CS_PerfectBot', views:'18.2K', likes:'2.1K', icon:'🗡️', description:'Full game commentary hitting 10 CS/min on Orianna mid' },
  { title:'5 Man Orianna Shockwave', author:'NeuralSmite', views:'31.7K', likes:'3.4K', icon:'⚙️', description:'Game-winning 5 man ult in ranked that ended a 45 minute game' },
  { title:'Lee Sin InSec Montage 2026', author:'FlashOnD_Always', views:'42.1K', likes:'5.2K', icon:'🥋', description:'Best InSec kicks compilation from Master+ games this season' },
  { title:'Bronze to Diamond: The Climb', author:'FreezeFrameTop', views:'15.8K', likes:'1.3K', icon:'📈', description:'Full timelapse of climbing from Bronze to Diamond in one month' },
  { title:'Thresh Lantern IQ 9000', author:'WardMother99', views:'28.3K', likes:'2.9K', icon:'⛓️', description:'Galaxy brain lantern play saves 3 teammates from certain death' }
];

const DISCUSSIONS = [
  { title:'Is Aatrox actually broken or just good?', author:'MidDiffGG', replies:47, views:'2.1K', preview:'Every game top lane is Aatrox. Is he actually OP or are people just not punishing him correctly?' },
  { title:'Best way to learn wave management?', author:'YasuoPowerspike', replies:32, views:'1.8K', preview:'Hardstuck Gold and I know my wave management is bad. What drills actually helped you improve?' },
  { title:'$1V9 token utility — what can we actually do with it?', author:'ProxySinged420', replies:28, views:'3.4K', preview:'I have been earning tokens through training. What are the planned features for spending them?' },
  { title:'Support mains: enchanter or engage in low elo?', author:'SupportCarry420', replies:53, views:'2.7K', preview:'Debating whether to play Nautilus/Leona or Lulu/Nami to climb out of Silver. Thoughts?' },
  { title:'The AI coach told me to stop fighting and I went up 2 divisions', author:'E_Girl_Lux_OTP', replies:41, views:'4.2K', preview:'Literally just followed the AI advice to focus on CS and wave management. Went from Gold 4 to Plat 2.' },
  { title:'Hottest TFT comp right now? Arcana or Bruiser?', author:'ARAMisLife', replies:19, views:'1.1K', preview:'Both seem strong but I keep getting contested on Arcana. Is Bruiser Bastion the safe pick?' }
];

const AI_RESPONSES = {
  cs: "CS is the foundation of League. Aim for 7+ CS/min — that alone puts you above 70% of players. Practice last hitting in the Training Arena with no abilities first, then add abilities. Focus on the cannon minion every wave — it's worth 60+ gold. Under tower: melee minions take 2 tower shots + 1 auto, casters take 1 auto + tower shot + 1 auto. Try our 'Last Hitting Basics' drill to build muscle memory.",
  ward: "Vision wins games. As a laner, use your trinket ward at 3:00-3:15 to catch the first jungle gank. Always ward river bushes or tri-bush depending on which side you're on. Supports should switch to sweeper after first back. Control wards in pixel brush or dragon/baron pit are extremely high value. Try our 'Ward Placement 101' technique to learn the essential spots.",
  trade: "Trading in lane is about punishing the enemy when they go for CS. Step forward when they auto a minion — they have to choose between the CS or trading back. Short trades (ability + auto + back off) are safer. Extended trades favor champions with sustained damage or healing. Always track enemy cooldowns and trade when their key ability is down.",
  macro: "Macro is about making the right decisions on the map. Key principles: 1) Push wave before roaming or taking objectives. 2) Be at dragon/baron 30 seconds before it spawns. 3) After winning a fight, take an objective — don't chase kills. 4) Look at your minimap every 5 seconds. 5) Play around your win condition, not just your lane.",
  jungle: "Jungle tracking is a game-changer. Watch for the enemy jungler on the minimap and note the time. Standard clears go buff→buff→gromp or buff→camp→buff. If you see the jungler bot side, top lane is safe to play aggressive. Ping when you spot them. Ward their camps at 1:15 if you can do it safely.",
  support: "Support impact comes from vision, roaming, and enabling your carry. In lane: match the enemy support's aggro — if they step up, you step up. After lane phase: ward objectives 60 seconds before they spawn, roam mid when your ADC is safe farming, and peel for your highest-DPS teammate in fights, not necessarily the ADC.",
  adc: "ADC is all about consistent DPS and positioning. In lane: focus on CS over fighting unless your support creates a clear opportunity. In teamfights: attack the closest target you can safely hit — don't tunnel on the backline. Kiting is essential: attack-move between autos. Build order matters: IE spike at 3 items is when you come online.",
  mid: "Mid lane has the most map impact. Shove wave → roam is the core pattern. Always have river warded. Your first back should include a component + control ward. Roam bot for dragon setup, top for herald. In teamfights, your job depends on your champion: assassins flank, mages zone, and control mages peel.",
  top: "Top lane is about wave management and 1v1 knowledge. Learn when to freeze (when ahead or vulnerable to ganks) vs push (when you want to roam or back). Teleport timing is crucial: TP to bot lane for dragon fights or to save a crashing wave. Match your playstyle to your champion — don't fight on tanks, don't AFK on fighters.",
  teamfight: "Team fight positioning depends on your role: Tanks — engage when your team can follow up, peel if your carry is threatened. Assassins — wait for key abilities to be used, then dive backline. ADCs — stay at max range, attack closest target safely. Mages — zone with abilities, stay behind frontline. Supports — peel your carry or engage based on champion.",
  climb: "To climb consistently: 1) Play 2-3 champions max. 2) Focus on CS — 7+ CS/min will carry you to Platinum alone. 3) Die less — most deaths below Diamond are avoidable. 4) Play around objectives, not kills. 5) Review your deaths after each game and ask 'was this avoidable?' The Training Arena techniques are ordered specifically to address the most impactful skills first.",
  tilt: "Tilt is your biggest enemy. When tilted, your decision-making drops by 20-30% based on our data analysis. Rules: 1) Stop after 2 losses in a row — take a 15 min break. 2) Mute toxic players immediately, don't engage. 3) Focus on your own gameplay, not teammates. 4) Physical reset: stretch, drink water, deep breaths. 5) Remember: one game doesn't define your skill.",
  default: "I can help with CS/last hitting, trading, wave management, macro play, jungle tracking, vision/warding, team fighting, climbing ranked, dealing with tilt, and role-specific advice (top/mid/adc/support/jungle). What would you like to focus on? You can also try our interactive Training Arena for hands-on practice."
};

